language: php

dist: trusty

sudo: false

services:
    - docker

addons:
    apt:
        packages:
            - docker-ce

cache:
    directories:
        - $HOME/.composer/cache/files

branches:
    only:
        - master

matrix:
    include:
        - php: '7.1'
          env: TARGET=test
        - php: '7.1'
          env: deps='low' TARGET=test
        - php: '7.1'
          env: deps='dev' TARGET=test
        - php: '7.1'
          env:  TARGET=check

before_install:
    - sudo service postgresql stop
    - sudo service mysql stop
    # wait for database servers to shutdown
    - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
    - while sudo lsof -Pi :3306 -sTCP:LISTEN -t; do sleep 1; done

    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    #- if [[ $coverage = 1 ]]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi

install:
    - |
        if [[ ! $deps ]]; then
            make install
        elif [[ $deps = 'dev' ]]; then
            make composer-install-dev
        elif [[ $deps = 'low' ]]; then
            make composer-install-lowest
        fi

script: make $TARGET

#after_success:
#    - if [[ $coverage = 1 ]]; then travis_retry php coveralls.phar --coverage_clover build/logs/clover.xml; fi
