version: '3'

services:
    php:
        depends_on:
          - elasticsearch
          - pgsql
          - mariadb-server
        image: rollerworks/search:latest
        working_dir: /project
        volumes:
            - .:/project:rw

    # Storage services
    pgsql:
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_DB=search_tests
            - POSTGRES_USER=postgres
        volumes:
            - pg-data:/var/lib/postgresql/data:rw
        ports:
            - "55432:5432"

    mariadb-server:
        image: mariadb
        restart: always
        environment:
            - MYSQL_DATABASE=search_tests
            - MYSQL_ROOT_PASSWORD=nope
        volumes:
            - my-data:/var/lib/mysql:rw
        ports:
            - "53306:3306"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
        environment:
            - "discovery.type=single-node"
            - "xpack.security.enabled=false"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - es-data:/usr/share/elasticsearch/data
        ports:
            - "59200:9200"

volumes:
    pg-data: {}
    my-data: {}
    es-data: {}
